site_name: AMPcamp-ja

repo_url: http://github.com/m-kiuchi/AMPcamp-jp

pages:
-  目次: index.md
- 1. はじめに: introduction.md
- 2. Spark SQL: spark-sql.md
- 3. Sparkストリーミング: spark-streaming.md
- 4. MLlib(機械学習): mllib.md
- 5. GraphX: graphx.md
- 6. SparkR: sparkr.md
- 7. パイプラインを使ってイメージ解析: pipeline.md
